version: '3.8'
services:
  vault:
    hostname: vault
    container_name: vault
    image: hashicorp/vault:latest
    entrypoint: vault server -config=/vault/config/config.hcl
    ports:
      - "8201:8200"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_API_ADDR: "http://0.0.0.0:8200"
    volumes:
      - "./conf:/vault/config"
      - "vault-data:/vault/data"
    cap_add:
      - IPC_LOCK

volumes:
  vault-data:
    driver: local
    name: vault-data