version: '3.8'

networks:
  k6:
  grafana:
  proxy:

services:
  influxdb:
    image: influxdb:1.8
    networks:
      - k6
      - grafana
      - proxy
    environment:
      - INFLUXDB_DB=k6
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.influxdb.entrypoints=websecure"
      - "traefik.http.routers.influxdb.rule=Host(`influxdb.teamdev.id`)"
      - "traefik.http.routers.influxdb.service=influxdb"
      - "traefik.http.services.influxdb.loadbalancer.server.port=8086"
 #     - "traefik.http.routers.influxdb.tls=true"

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    networks:
      - proxy
      - grafana
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.rule=Host(`grafana.teamdev.id`)"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
#      - "traefik.http.routers.grafana.tls=true"

  chronograf:
    image: chronograf:1.8
    ports:
      - "8888:8888"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=root
      - INFLUXDB_PASSWORD=root
      - INFLUXDB_SKIP_VERIFY=true
    depends_on:
      - influxdb
    networks:
      - k6
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.chronograf.entrypoints=websecure"
      - "traefik.http.routers.chronograf.rule=Host(`chronograf.teamdev.id`)"
      - "traefik.http.routers.chronograf.service=chronograf"
      - "traefik.http.services.chronograf.loadbalancer.server.port=8888"
  #    - "traefik.http.routers.chronograf.tls=true"

  k6:
    image: grafana/k6
    networks:
      - k6
      - proxy
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./scripts:/scripts
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.k6.entrypoints=websecure"
      - "traefik.http.routers.k6.rule=Host(`k6.teamdev.id`)"
      - "traefik.http.routers.k6.service=k6"
      - "traefik.http.services.k6.loadbalancer.server.port=6565"
   #   - "traefik.http.routers.k6.tls=true"