version: '3'

services:
  locust:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./load_tests/:/mnt/locust
    command: -f /mnt/locust/locustfile.py
    # depends_on:
    #   - api

# services:
#   locust:
#     image: locustio/locust
#     ports:
#      - "8089:8089"
#     volumes:
#       - ./:/mnt/locust
#     command: -f /mnt/locust/locustfile.py --master -H http://master:8089
  
  # worker:
  #   image: locustio/locust
  #   volumes:
  #     - ./:/mnt/locust
  #   command: -f /mnt/locust/locustfile.py --worker --master-host master
